server.port=78

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/farmacia?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sebascr16048

# Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
